name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Universe!!!" 
      - name: Print Goodbye
        run: echo "Tatty Bye..."
      - name: Multiple Lines
        run: |
            echo "First Line"
            echo "Second Line"
